export const FETCH_MOVIES = 'HOME_ACTION_FETCH_MOVIES';
export const FETCH_MOVIES_START = 'HOME_ACTION_FETCH_MOVIES_START';
export const FETCH_MOVIES_FINISH = 'HOME_ACTION_FETCH_MOVIES_FINISH';
export const FETCH_MOVIES_SUCCESS = 'HOME_ACTION_FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'HOME_ACTION_FETCH_MOVIES_FAILURE';
export const ADD_MOVIE_TO_FAVOURITES = 'HOME_ACTION_ADD_MOVIE_TO_FAVOURITES';
